[2025-07-31T02:44:57.028+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bq_dag.load_existing_bq_table manual__2025-07-31T02:44:54.111786+00:00 [queued]>
[2025-07-31T02:44:57.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bq_dag.load_existing_bq_table manual__2025-07-31T02:44:54.111786+00:00 [queued]>
[2025-07-31T02:44:57.040+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-31T02:44:57.058+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSToBigQueryOperator): load_existing_bq_table> on 2025-07-31 02:44:54.111786+00:00
[2025-07-31T02:44:57.077+0000] {standard_task_runner.py:60} INFO - Started process 735 to run task
[2025-07-31T02:44:57.084+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_dag', 'load_existing_bq_table', 'manual__2025-07-31T02:44:54.111786+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmp_c9di6yt']
[2025-07-31T02:44:57.089+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask load_existing_bq_table
[2025-07-31T02:44:57.165+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_to_bq_dag.load_existing_bq_table manual__2025-07-31T02:44:54.111786+00:00 [running]> on host e63302d63f25
[2025-07-31T02:44:57.422+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bq_dag' AIRFLOW_CTX_TASK_ID='load_existing_bq_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T02:44:54.111786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T02:44:54.111786+00:00'
[2025-07-31T02:44:57.453+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-07-31T02:44:57.467+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-07-31T02:44:57.471+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2025-07-31T02:44:57.547+0000] {bigquery.py:2312} INFO - Project is not included in destination_project_dataset_table: your_dataset.your_table; using project "target-de"
[2025-07-31T02:44:57.549+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'target-de', 'datasetId': 'your_dataset', 'tableId': 'your_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://sp500-***-de-project/sp500-dataset/sp500.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2025-07-31T02:44:57.552+0000] {bigquery.py:1596} INFO - Inserting job ***_gcs_to_bq_dag_load_existing_bq_table_2025_07_31T02_44_54_111786_00_00_2f18ec37133c749445b0bf3fb73b2f88
[2025-07-31T02:44:58.509+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 384, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 306, in _submit_job
    return hook.insert_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 477, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1599, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 818, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/target-de/jobs?prettyPrint=false: Not found: Dataset target-de:your_dataset
[2025-07-31T02:44:58.594+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=gcs_to_bq_dag, task_id=load_existing_bq_table, execution_date=20250731T024454, start_date=20250731T024457, end_date=20250731T024458
[2025-07-31T02:44:58.629+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task load_existing_bq_table (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/target-de/jobs?prettyPrint=false: Not found: Dataset target-de:your_dataset; 735)
[2025-07-31T02:44:58.669+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-31T02:44:58.701+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
